name: Smoke test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment
        required: true
        default: dev

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Smoke tests against ${{ github.event.inputs.environment }}
        run: yarn smoke-tests
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
