name: Telegram notification

on:
  push:
    branches:
      - main

jobs:
  send-telegram-notification:
    uses: andrelopesmds/reusable-workflows/.github/workflows/telegram-notification.yml@main
    with:
      message: 'goalstracker-api merged to main'
    secrets: inherit
